# SPDX-License-Identifier: Apache-2.0
"""WASD walking, generated by MotionBricks, for the force policy to track.

The force policy is a mimic tracker: it follows a reference and has no notion of a velocity command.
Steering it from a keyboard therefore needs something upstream that *invents* a reference, and
MotionBricks (NVIDIA's real-time latent motion model, part of GR00T Whole-Body Control) is a good
fit for the job in a way a diffusion sampler is not:

* it is an interactive controller by construction -- one frame per call from a direction and a
  locomotion mode, which is exactly what a keyboard produces;
* its default mode *is* ordinary walking, with the pelvis rising and falling ~7 cm as a real gait
  does, rather than whatever a prior happens to sample;
* it runs far faster than real time, so the reference can be produced a fraction of a second ahead
  of the robot instead of a second or two, which keeps steering responsive.

The pieces line up without conversion: MotionBricks emits MuJoCo ``qpos`` for the 29-DoF G1 in the
same joint order as the policy contract (asserted below), so a frame is copied across positionally
and :class:`ReferenceBuilder` turns it into the body-frame fields the policy observes.

**Commands are directions, not speeds.** MotionBricks takes a world-frame movement direction, a
facing direction, and a mode; the speed belongs to the mode. So a WASD command is resolved here into
a heading (integrated from the turn keys), a direction in that frame, and a mode chosen by how fast
the operator asked to go -- ``idle`` when they asked for nothing.

**Closing the loop.** Generation continues from a context window of qpos, so the generator has to be
told something about the robot -- a kinematic reference is not something a physical gait matches
exactly, and left to its own output the reference wanders away from the robot for as long as a key
is held. What it must *not* be told is the robot's raw pose: the model blends the context it is
given into the frames it produces, and since the robot is behind, every generation then restarts
behind the frames already emitted. The reference lurches backwards, walks forward, lurches again --
measured, one frame in twenty went backwards, the worst by 35 cm, against 3 cm of normal per-frame
travel. Instead the context stays the generator's own pose with its root nudged toward the robot by
a capped step, which corrects the same drift a few millimetres at a time. See
:meth:`set_context_qpos`.
"""

from __future__ import annotations

import math
import xml.etree.ElementTree as ET
from pathlib import Path

import numpy as np

from .reference_frames import ReferenceBuilder

# MotionBricks generates at this rate; the reference is resampled to the contract's control rate.
MOTIONBRICKS_FPS = 30.0
# Frames of generated motion kept ahead of the consumer. Small on purpose: the generator is faster
# than real time, and everything buffered was produced under an older command, so depth is latency.
LEAD_FRAMES = 12
# The styles offered to an operator, in the order the number keys select them.
#
# MotionBricks carries more than these -- the crawls in particular -- and they are left out because
# the force policy cannot track them: asked to hand-crawl it ends up on the floor within a couple of
# seconds (measured, and unsurprising, since crawling is nowhere near what a walking tracker was
# trained on). Everything listed here was measured tracking upright at 0.06-0.18 rad of joint error.
STYLES: tuple[str, ...] = (
    "walk",
    "slow_walk",
    "stealth_walk",
    "walk_boxing",
    "injured_walk",
    "walk_happy_dance",
    "walk_zombie",
    "walk_gun",
    "walk_scared",
)

# Below this commanded speed, in m/s, the robot is asked to stand rather than to walk.
IDLE_SPEED = 0.05
# Beyond this angle between travel and facing, use the slow clip. Just under a right angle, so
# strafing and backing up are slow while a gentle diagonal still walks at pace.
OFF_AXIS_SLOW_RAD = math.radians(75.0)
# How fast the direction of travel may change, degrees per second.
#
# Keys change instantly and a body cannot: going from A to D reverses the requested direction by 180
# degrees between one frame and the next, and a robot in mid-stride is asked to be travelling the
# other way immediately. Measured, that is enough to put it on the floor. Turning the request into a
# rate-limited sweep costs about a second and a half for a full reversal.
DIRECTION_SLEW_DEG_S = 120.0
# Fastest turn the gait can actually follow, degrees per second.
#
# This is a measured limit, not a taste: the generator is steered by a facing *direction*, and past
# about twenty degrees a second the walk cannot keep up with one that rotates. What comes out is not
# merely slower -- it aliases. Commanding 20 gives 20, 25 gives -20, 45 gives 0 and 60 gives +15, so
# the robot turns the wrong way or not at all while visibly fighting the reference. Clamping keeps
# the command inside the envelope; a sharper turn is a longer press, not a faster rate.
MAX_TURN_DEG_S = 20.0
# Most the reference's root may be nudged per generated frame, in metres, and the fraction of the
# measured error aimed for. The cap is what keeps the reference continuous, and it was chosen by
# measuring where the reference stops ever stepping backwards: at 2 mm the worst backward step is
# 9 mm against 30 mm of normal per-frame travel and nothing exceeds a centimetre, while five times
# that leaves visible 3 cm reversals. Slower correction costs only a slightly looser follow (a
# steady 0.23 m behind, against 0.16 m).
CORRECTION_STEP_M = 0.002
CORRECTION_GAIN = 0.15
# One cap for every mode, deliberately. Correcting harder while the robot is standing is tempting
# -- a stationary reference has no gait to disturb -- but the generator amplifies a shifted context
# rather than following it exactly, and a boosted idle correction put a 25 cm jump back into the
# reference: the same visible artefact this cap exists to prevent.


def _yaw_of(quat_wxyz) -> float:
    """Heading about world up, in radians, from a ``wxyz`` quaternion."""
    w, x, y, z = (float(v) for v in quat_wxyz[:4])
    return math.atan2(2.0 * (w * z + x * y), 1.0 - 2.0 * (y * y + z * z))


class MotionBricksStream:
    """Reference frames at the control rate, generated on demand from a live velocity command.

    Deliberately the same interface the other generators in this package expose -- ``set_command``,
    ``frames``, ``available`` -- so the runner, the websocket server and the browser client are
    indifferent to which one is behind them.
    """

    def __init__(
        self,
        contract: dict,
        mjcf: Path,
        motionbricks_root: Path,
        seed: int | None = None,
        device: str = "cuda",
        mode: str = "walk",
    ) -> None:
        import torch

        self._torch = torch
        self._builder = ReferenceBuilder(contract, mjcf)
        self.control_dt = self._builder.control_dt
        self._assert_joint_order(motionbricks_root, self._builder.joint_names)
        self._walk_mode = mode

        self._agent, self._controller, self._modes, self._horizon_dt = self._load_agent(
            motionbricks_root, seed, device
        )
        # Real time between generated frames. Distinct from `_horizon_dt`, which is how far ahead a
        # generation call is asked to produce -- twenty times longer. Integrating the heading with
        # the horizon by mistake turns a 45 deg/s command into roughly 700.
        self._frame_dt = 1.0 / MOTIONBRICKS_FPS
        self._agent.reset()

        # The operator's command, in the robot's own frame: m/s, m/s, deg/s.
        self._command = (0.0, 0.0, 0.0)
        # Heading the command is resolved against, integrated from the turn key.
        self._heading = 0.0
        # Direction of travel actually asked for, swept towards the commanded one. See
        # `DIRECTION_SLEW_DEG_S`.
        self._move_angle: float | None = None
        # Where the consumer's robot is and which way it faces, plus the reference frame it is
        # tracking; used to nudge the generator rather than to replace its context. See
        # `set_context_qpos`.
        self._robot_xy: np.ndarray | None = None
        self._robot_yaw: float | None = None
        self._robot_frame: int | None = None
        # Accumulated root offset applied to the context, in world metres.
        self._correction = np.zeros(2)

        self._qpos = np.zeros((0, 7 + len(self._builder.joint_names)))
        self._reference: dict[str, np.ndarray] | None = None

    # -- setup ------------------------------------------------------------------

    @staticmethod
    def _assert_joint_order(root: Path, joint_names: list[str]) -> None:
        """MotionBricks' G1 hinge order must equal the contract's -- qpos is copied positionally."""
        xml = ET.parse(root / "assets" / "skeletons" / "g1" / "g1.xml").getroot()
        theirs = [j.get("name") for j in xml.find("worldbody").findall(".//joint")]
        if theirs != list(joint_names):
            raise ValueError("MotionBricks g1.xml joint order differs from the policy contract's")

    def _load_agent(self, root: Path, seed: int | None, device: str):
        """Build the MotionBricks navigation agent, headless.

        Imported lazily and with the working directory pinned: its loader resolves checkpoints and
        assets relative to its own tree, and it is an optional dependency of this package.
        """
        import argparse
        import os

        import torch

        if seed is not None:
            torch.manual_seed(seed)
            np.random.seed(seed)

        previous = os.getcwd()
        os.chdir(root)
        try:
            from motionbricks.motion_backbone.demo.clips import clip_holder_G1
            from motionbricks.motion_backbone.demo.utils import navigation_demo

            args = argparse.Namespace(
                humanoid_xml="assets/skeletons/g1/scene_29dof.xml",
                result_dir="./out",
                data_root="./datasets",
                explicit_dataset_folder=None,
                reprocess_clips=0,
                controller="wasd",
                lookat_movement_direction=0,
                # No viewer: this is a reference source, and the robot it drives is elsewhere.
                has_viewer=0,
                pre_filter_qpos=1,
                source_root_realignment=1,
                target_root_realignment=1,
                force_canonicalization=1,
                skip_ending_target_cond=0,
                random_speed_scale=0,
                speed_scale=[1.0, 1.0],
                generate_dt=2.0,
                max_steps=10**9,
                random_seed=1234 if seed is None else seed,
                num_runs=1,
                use_qpos=1,
                planner="default",
                allowed_mode=None,
                clips="G1",
                return_model_configs=True,
                return_dataloader=True,
                recording_dir=None,
                EXP="default",
            )
            demo = navigation_demo(args)
        finally:
            os.chdir(previous)

        modes = list(clip_holder_G1.CLIPS.keys())
        if self._walk_mode not in modes:
            raise ValueError(f"unknown MotionBricks mode {self._walk_mode!r}; have {modes}")
        generate_dt = demo.controller.get_controller_dt() * args.generate_dt
        return demo.full_agent, demo.controller, modes, generate_dt

    def reset(self) -> None:
        """Start a fresh session on the already-loaded model.

        Loading the checkpoints costs a couple of minutes, so a server keeps one stream and resets
        it between clients rather than building another.
        """
        self._agent.reset()
        self._command = (0.0, 0.0, 0.0)
        self._heading = 0.0
        self._move_angle = None
        self._robot_xy = None
        self._robot_yaw = None
        self._robot_frame = None
        self._correction = np.zeros(2)
        self._qpos = np.zeros((0, 7 + len(self._builder.joint_names)))
        self._reference = None

    # -- command ----------------------------------------------------------------

    @property
    def styles(self) -> tuple[str, ...]:
        """The styles this generator will accept, in selection order."""
        return tuple(name for name in STYLES if name in self._modes)

    @property
    def style(self) -> str:
        """The style currently selected."""
        return self._walk_mode

    def set_style(self, name: str) -> None:
        """Choose the locomotion style. Takes effect on the next generated frame."""
        if name not in self._modes:
            raise ValueError(f"unknown style {name!r}; have {self.styles}")
        self._walk_mode = name

    def set_command(self, forward: float, lateral: float, turn_deg: float) -> None:
        """Set the velocity command, in the robot's own frame (m/s, m/s, deg/s).

        The turn rate is clamped to :data:`MAX_TURN_DEG_S`, because a faster one does not come out
        faster -- it comes out wrong.
        """
        turn = max(-MAX_TURN_DEG_S, min(MAX_TURN_DEG_S, float(turn_deg)))
        self._command = (float(forward), float(lateral), turn)

    @property
    def command(self) -> tuple[float, float, float]:
        return self._command

    def set_context_qpos(self, qpos: np.ndarray, frame: int | None = None) -> None:
        """Report the consumer's robot pose, and the reference frame it is currently tracking.

        Only the root position is used, and only to steer the correction: ``frame`` says which
        reference frame the robot is on, which is what makes the comparison fair -- measuring
        against the newest generated frame instead would read the whole look-ahead buffer as error
        and over-correct by however deeply the consumer buffers.
        """
        pose = np.asarray(qpos, dtype=np.float64)
        self._robot_xy = pose[:2].copy()
        self._robot_yaw = _yaw_of(pose[3:7])
        self._robot_frame = None if frame is None else int(frame)

    def _signals(self) -> dict:
        """The control signals for one generation step: direction, facing, mode, context."""
        torch = self._torch
        forward, lateral, turn = self._command
        speed = math.hypot(forward, lateral)

        # Facing and travel are separate quantities, and only the turn keys move the facing. This is
        # what makes "go back" and "step sideways" expressible at all: deriving the facing from the
        # travel direction turns S into "face backward and walk", which the correction then reads as
        # a 180-degree heading error to be removed -- and S, A and D all came out as forward walking
        # at about 1 m/s while only W and the turn keys did as asked.
        # The facing runs open-loop from the command, and nothing pulls it back towards the robot.
        # Both ways of tying it to the robot were tried and are worse. Rotating the generator's
        # context towards the robot *reverses* a turn once the correction saturates -- a +20 deg/s
        # command measured -9. Clamping the facing to a bounded lead instead is self-limiting: the
        # heading can only advance as fast as the thing it is clamped to already turns, so it needs
        # a strong response to bootstrap. A local loop provides that; the browser does not, and a
        # held turn key did nothing at all there while the reference sat 60 degrees off the robot.
        #
        # What made heading feedback look necessary in the first place was the facing being derived
        # from the travel direction: any positional correction then rotated the operator's intent.
        # With the two separated, the position correction alone holds the two together -- measured
        # over every key, the gap is 0.07-0.25 m without heading feedback, tighter than the 0.11-0.35
        # it managed with it, and the turn keys reach the full commanded rate.
        self._heading += math.radians(turn) * self._frame_dt
        facing_angle = self._heading

        # Travel: the commanded offset from the facing, swept rather than snapped. Keys change
        # instantly and a body cannot -- going from A to D reverses the request by 180 degrees
        # between one frame and the next, which is enough to put the robot on the floor.
        if speed > IDLE_SPEED:
            target = facing_angle + math.atan2(lateral, forward)
            if self._move_angle is None:
                self._move_angle = target
            else:
                error = (target - self._move_angle + math.pi) % (2.0 * math.pi) - math.pi
                limit = math.radians(DIRECTION_SLEW_DEG_S) * self._frame_dt
                self._move_angle += max(-limit, min(limit, error))
        else:
            self._move_angle = facing_angle

        facing = np.array([math.cos(facing_angle), math.sin(facing_angle), 0.0])
        movement = np.array([math.cos(self._move_angle), math.sin(self._move_angle), 0.0])

        mode_index = torch.tensor([[self._modes.index(self.current_mode())]])

        context = self._context_window()
        signals = {
            "movement_direction": torch.from_numpy(movement).float().view(1, -1),
            "facing_direction": torch.from_numpy(facing).float().view(1, -1),
            "mode": mode_index,
            "context_mujoco_qpos": context,
        }
        signals["allowed_pred_num_tokens"] = self._controller.get_default_allowed_pred_num_tokens(
            mode_index.item()
        )
        return signals

    def chain_state(self) -> str:
        """heading / reference yaw / robot yaw, in degrees -- for diagnostics."""
        ref = float("nan")
        if self._reference is not None and self._reference["body_quat_w"].shape[0]:
            quats = self._reference["body_quat_w"]
            # The frame the consumer says it is tracking, not the newest generated one: comparing
            # against the newest counts the whole look-ahead buffer as tracking error.
            index = quats.shape[0] - 1 if self._robot_frame is None else self._robot_frame
            index = max(0, min(index, quats.shape[0] - 1))
            ref = math.degrees(_yaw_of(quats[index, 0]))
        robot = float("nan") if self._robot_yaw is None else math.degrees(self._robot_yaw)
        return "head=%+7.1f ref=%+7.1f robot=%+7.1f" % (
            math.degrees(self._heading), ref, robot)

    def reference_speed(self) -> float:
        """Recent speed of the generated reference itself, m/s -- for diagnostics."""
        if self._qpos.shape[0] < 20:
            return float("nan")
        span = self._qpos[-20:, :2]
        return float(np.linalg.norm(span[-1] - span[0])) / (19.0 / MOTIONBRICKS_FPS)

    def current_mode(self) -> str:
        """The clip the current command and style select.

        Standing still and travelling off-axis override the chosen style. The speed of a reference
        comes from its clip rather than from the commanded magnitude, and every style here is a
        *forward* gait carried at around a metre a second in whatever direction it is pointed --
        which the policy tracks forwards and falls over backwards. Sideways and backward therefore
        drop to the slow walk whatever style is selected.
        """
        forward, lateral, _ = self._command
        if math.hypot(forward, lateral) <= IDLE_SPEED:
            return "idle"
        off_axis = abs((math.atan2(lateral, forward) + math.pi) % (2.0 * math.pi) - math.pi)
        if off_axis > OFF_AXIS_SLOW_RAD and "slow_walk" in self._modes:
            return "slow_walk"
        return self._walk_mode

    def tracking_error(self) -> float:
        """Distance from the consumer's robot to the reference frame it reported tracking, in metres."""
        if self._robot_xy is None or self._reference is None:
            return float("nan")
        frames = self._reference["body_pos_w"]
        index = frames.shape[0] - 1 if self._robot_frame is None else self._robot_frame
        index = max(0, min(index, frames.shape[0] - 1))
        return float(np.linalg.norm(self._robot_xy - frames[index, 0, :2]))

    def _advance_correction(self) -> None:
        """Take one capped step of the root position correction towards the robot.

        Position only. Rotating the context towards the robot as well is the obvious counterpart and
        it does not work: the generator answers a rotated context with a turn of its own, so once the
        correction saturates it cancels and then reverses the operator's turn. Heading is kept in
        reach by bounding the command's lead instead -- see `_signals`.
        """
        if self._robot_xy is None or self._reference is None:
            return
        positions = self._reference["body_pos_w"]
        index = positions.shape[0] - 1 if self._robot_frame is None else self._robot_frame
        index = max(0, min(index, positions.shape[0] - 1))

        error = self._robot_xy - positions[index, 0, :2]
        step = CORRECTION_GAIN * error - self._correction
        length = float(np.linalg.norm(step))
        if length > CORRECTION_STEP_M:
            step *= CORRECTION_STEP_M / length
        self._correction = self._correction + step

    def _context_window(self):
        """The generator's own context, shifted towards the robot by the accumulated correction.

        Shifting the whole window by one offset leaves the velocities inside it untouched, so the
        generator reads the same gait it was producing, merely a few millimetres closer to the
        robot. Replacing the window with the robot's poses instead is what makes the reference
        lurch; filling it with one repeated pose describes a robot standing still, and it answers
        with a near-standstill (measured: 0.19 m/s against 0.8 m/s commanded).
        """
        own = self._agent.get_context_mujoco_qpos()
        if not self._correction.any():
            return own
        shifted = own.clone()
        shifted[:, :, 0] += float(self._correction[0])
        shifted[:, :, 1] += float(self._correction[1])
        return shifted

    # -- generation -------------------------------------------------------------

    def _generate_frame(self) -> None:
        """Take one frame from the generator and advance it."""
        torch = self._torch
        self._advance_correction()
        qpos = np.asarray(self._agent.get_next_frame(), dtype=np.float64)
        self._qpos = np.concatenate([self._qpos, qpos[None, :]], axis=0)
        with torch.no_grad():
            self._agent.generate_new_frames(self._signals(), self._horizon_dt)

    @property
    def available(self) -> int:
        """Reference frames decoded so far, at the control rate."""
        return 0 if self._reference is None else self._reference["joint_pos"].shape[0]

    def ensure(self, index: int) -> None:
        """Generate until frame ``index`` exists."""
        if self.available > index:
            return
        while True:
            # Two generated frames make roughly three at the control rate, plus a margin so the
            # finite-difference velocities at the end have a neighbour to look at.
            needed = int(math.ceil((index + LEAD_FRAMES) * self.control_dt * MOTIONBRICKS_FPS)) + 2
            while self._qpos.shape[0] < needed:
                self._generate_frame()
            self._reference = self._builder.build(self._qpos, MOTIONBRICKS_FPS)
            if self.available > index:
                return

    def frames(self, indices) -> dict[str, np.ndarray]:
        """Reference fields at ``indices`` (an int or a sequence), generating as needed."""
        idx = np.atleast_1d(np.asarray(indices, dtype=np.int64))
        self.ensure(int(idx.max()))
        return {key: value[idx] for key, value in self._reference.items()}
