// Run against serve_dist + wasd_server with NODE_PATH pointing at mjswan's node_modules.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ args: ['--no-sandbox', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(process.env.BRACE_TEST_URL || 'http://127.0.0.1:8080/?stream=ws%3A%2F%2F127.0.0.1%3A8765');
    await page.getByRole('button', { name: 'Careful', exact: true }).waitFor({ timeout: 90000 });
    await page.locator('.brace-style[aria-label="Stealth"][aria-pressed="true"]').waitFor();
    await page.waitForFunction(()=>window.BraceGym?.ready,null,{timeout:90000});
    console.log('PASS new session starts in Stealth');
    await page.getByRole('button', { name: 'Forces & interaction', exact: true }).click();
    const widget = page.getByRole('region', { name: 'Quick force controls' });
    const status = widget.getByRole('status');
    const values = () => page.locator('.brace-force-section').evaluateAll(sections => Object.fromEntries(sections.map(s => [s.firstElementChild.textContent.trim(), { mode: s.querySelector('input[type=checkbox]')?.checked, values: [...s.querySelectorAll('[role=slider]')].map(e => Number(e.getAttribute('aria-valuenow'))) }])));
    await widget.getByRole('button', { name: 'Apply 10 newtons', exact: true }).click();
    await status.filter({ hasText: 'Compensating 10 N' }).waitFor();
    let native = await values();
    assert.deepEqual(native['Hand Force'].values, [0, 0, 0, 10, 0, 0]);
    assert.equal(native.Exert.mode, false);
    await page.waitForFunction(()=>Math.abs(window.BraceGym.force().reaction[1][0]-10)<.001);
    console.log('PASS compensation preset applies 10 N to the actual MuJoCo force buffer');
    await widget.getByRole('button', { name: 'Exert', exact: false }).click();
    await status.filter({ hasText: 'No force applied.' }).waitFor();
    await widget.getByRole('button', { name: 'Apply 8 newtons', exact: true }).click();
    await status.filter({ hasText: 'Exerting 8 N' }).waitFor();
    native = await values();
    assert.deepEqual(native['Hand Force'].values, [0, 0, 0, 0, 0, 0]);
    assert.deepEqual(native.Exert.values, [0, 0, 0, 8, 0, 0]);
    assert.equal(native.Exert.mode, true);
    console.log('PASS exert preset enables brace and clears compensation');
    await widget.getByRole('combobox', { name: 'Force hand' }).selectOption('both');
    await status.filter({ hasText: 'No force applied.' }).waitFor();
    await widget.getByRole('combobox', { name: 'Force direction' }).selectOption('Z:-1');
    await widget.getByRole('spinbutton', { name: 'Custom force in newtons' }).fill('3.25');
    await widget.getByRole('button', { name: 'Apply force', exact: true }).click();
    await status.filter({ hasText: 'Exerting 3.25 N per hand' }).waitFor();
    native = await values();
    assert.deepEqual(native.Exert.values, [0, 0, -3.25, 0, 0, -3.25]);
    await widget.getByRole('button', { name: 'Clear force', exact: true }).click();
    await status.filter({ hasText: 'No force applied.' }).waitFor();
    native = await values();
    assert.equal(native.Exert.mode, false);
    assert(native.Exert.values.every(v => v === 0));
    assert(native['Hand Force'].values.every(v => v === 0));
    await page.waitForFunction(()=>window.BraceGym.force().reaction.every(v=>Math.hypot(...v)<.001));
    console.log('PASS signed custom force, both hands, and clear');
    await widget.getByRole('button', { name: 'Compensate', exact: false }).click();
    await widget.getByRole('button', { name: 'Apply 20 newtons', exact: true }).click();
    await status.filter({ hasText: 'Compensating 20 N per hand' }).waitFor();
    native = await values();
    assert.deepEqual(native['Hand Force'].values, [0, 0, -20, 0, 0, -20]);
    await page.waitForFunction(()=>window.BraceGym.force().reaction.every(v=>Math.abs(v[2]+20)<.001));
    await widget.getByRole('spinbutton', { name: 'Custom force in newtons' }).fill('25');
    await widget.getByRole('button', { name: 'Apply force', exact: true }).click();
    assert.equal(await widget.getByRole('spinbutton').evaluate(e => e.validity.rangeOverflow), true);
    assert.deepEqual((await values())['Hand Force'].values, native['Hand Force'].values);
    await widget.getByRole('button', { name: 'Clear force', exact: true }).click();
    await status.filter({ hasText: 'No force applied.' }).waitFor();
    console.log('PASS total two-hand compensation budget and invalid input rejection');
    await widget.getByRole('button', { name: 'Individual axes', exact: true }).click();
    assert(await page.getByRole('slider', { name: 'Load on right hand X (N)' }).isVisible());
    await widget.getByRole('button', { name: 'Individual axes', exact: true }).click();
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    assert.equal(await widget.evaluate(e => e.scrollWidth > e.clientWidth), false);
    assert.deepEqual(errors, []);
    console.log('PASS advanced controls, 390 px mobile layout, and no page errors');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
