const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.BRACE_TEST_URL||'http://127.0.0.1:8080/?stream=ws%3A%2F%2F127.0.0.1%3A8765');await page.waitForFunction(()=>window.BraceGym?.ready&&window.BraceReference?.policyAnchorXY.length===2,null,{timeout:90000});
const snapshot=()=>page.evaluate(()=>({ref:window.BraceReference,force:window.BraceGym.force()}));
function aligned(s){assert.equal(s.ref.mode,'body');assert(Math.hypot(...s.ref.policyAnchorXY)<1e-5);assert(Math.hypot(...s.ref.displayAnchor.map((v,i)=>v-s.ref.robotAnchor[i]))<1e-5);assert(s.force.root[2]>.6);}
aligned(await snapshot());await page.keyboard.down('w');for(let i=0;i<8;i++){await page.waitForTimeout(1000);aligned(await snapshot());}await page.keyboard.up('w');console.log('PASS walking: reference anchor follows robot, policy XY origin stays zero, no fall');
await page.getByLabel('Reference view',{exact:true}).selectOption('world');await page.waitForTimeout(300);let world=await snapshot();assert.equal(world.ref.mode,'world');assert.deepEqual(world.ref.displayAnchor,world.ref.sourceAnchor);assert(Math.hypot(...world.ref.policyAnchorXY)<1e-5);console.log('PASS world view exposes original trajectory without changing policy origin');
await page.getByLabel('Reference view',{exact:true}).selectOption('body');await page.getByRole('button',{name:'Reset',exact:true}).click();await page.waitForFunction(()=>window.BraceGym.ready,null,{timeout:90000});await page.getByRole('button',{name:'Exert force',exact:true}).click();await page.getByRole('button',{name:'Apply 5 newtons',exact:true}).click();await page.waitForTimeout(12000);let exert=await snapshot();aligned(exert);const reading=await page.evaluate(()=>window.BraceExert.reading);assert(Math.abs(reading.measured[1]-Math.hypot(...reading.commanded.slice(3,6)))<1);console.log('PASS canonical reference retains 5 N spring force tracking');
await page.getByRole('button',{name:'Reset',exact:true}).click();await page.waitForFunction(()=>window.BraceGym.ready,null,{timeout:90000});aligned(await snapshot());if(process.env.BRACE_SCREENSHOT)await page.screenshot({path:process.env.BRACE_SCREENSHOT});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS reset, mobile and browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
