const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const c=await b.newContext({viewport:{width:1100,height:900}});
 await c.addInitScript(()=>{window.__moves=[];const W=window.WebSocket;window.WebSocket=class extends W{send(data){try{const v=JSON.parse(data);if(v.type==='command')window.__moves.push(v)}catch{}super.send(data)}}});
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(process.env.BRACE_TEST_URL||'http://127.0.0.1:8080/?stream=ws%3A%2F%2F127.0.0.1%3A8765');await p.waitForFunction(()=>window.BraceGym?.ready,null,{timeout:120000});
 await p.getByRole('button',{name:'Exert force',exact:true}).click();await p.getByRole('button',{name:'Apply 8 newtons',exact:true}).click();
 await p.waitForFunction(()=>window.BraceSteering?.blockedKeys.includes('s'));
 const s=p.getByRole('button',{name:'Walk backward',exact:true}),turn=p.getByRole('button',{name:'Turn left',exact:true});
 assert.equal(await s.getAttribute('aria-disabled'),'true');await p.keyboard.press('s');await s.dispatchEvent('pointerdown',{pointerId:1});assert(!(await p.evaluate(()=>window.__moves)).some(v=>v.forward<0));
 await p.keyboard.down('w');await p.keyboard.down('q');await p.waitForFunction(()=>window.__moves.at(-1)?.forward>0&&window.__moves.at(-1)?.turn===5);
 assert.equal(await turn.getAttribute('aria-disabled'),'false');await p.keyboard.up('q');await p.keyboard.up('w');
 await p.keyboard.down('a');await p.waitForFunction(()=>window.__moves.at(-1)?.lateral>0);await p.keyboard.up('a');
 await s.hover();assert.match(await s.getAttribute('title'),/Backward movement directly opposes the forward hand push/);assert.match(await p.locator('.brace-steering-tooltip').innerText(),/Temporarily disabled/);
 assert.equal(await p.locator('.brace-controls #brace-stability-test').count(),1);assert.equal(await p.locator('.brace-header #brace-stability-test').count(),0);
 await p.getByRole('combobox',{name:'Force direction',exact:true}).selectOption('X:-1');await p.getByRole('button',{name:'Apply 8 newtons',exact:true}).click();
 await p.waitForFunction(()=>window.BraceSteering?.blockedKeys.includes('w'));assert.equal(await p.getByRole('button',{name:'Walk forward',exact:true}).getAttribute('aria-disabled'),'true');assert.equal(await s.getAttribute('aria-disabled'),'false');
 await p.keyboard.down('e');await p.waitForFunction(()=>window.__moves.at(-1)?.forward<0&&window.__moves.at(-1)?.turn===-2);await p.keyboard.up('e');
 await p.getByRole('button',{name:'Clear force',exact:true}).click();await p.waitForFunction(()=>window.BraceSteering.blockedKeys.length===0);
 await p.keyboard.down('s');await p.waitForFunction(()=>window.__moves.at(-1)?.forward<0);await p.keyboard.up('s');await p.keyboard.down('q');await p.waitForFunction(()=>window.__moves.at(-1)?.turn===20);await p.keyboard.up('q');
 assert.deepEqual(errors,[]);console.log('PASS keyboard/pointer opposite blocking; forward+turn and sides enabled; backward arc; hover explanation; clear restores steering');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
