const assert=require('node:assert/strict'),fs=require('node:fs'),Module=require('node:module'),esbuild=require('esbuild');
function load(path,loader='js'){const m=new Module(`${process.env.NODE_PATH}/test-${loader}.cjs`);m.filename=m.id;m.paths=Module._nodeModulePaths(process.env.NODE_PATH);m._compile(esbuild.transformSync(fs.readFileSync(path,'utf8'),{loader,format:'cjs'}).code,m.filename);return m.exports;}
global.window=new EventTarget();window.BraceExert={enabled:true};global.CustomEvent=class extends Event{};
const source=Object.create(load('assets/liveMotion.ts','ts').LiveMotionSource.prototype);source.command=[0,0,0];source.pressed=new Set();const messages=[];source.socket={readyState:1,send:s=>messages.push(JSON.parse(s))};source.renderKeys=source.paintKeys=source.setFocused=()=>{};source.attachKeyboard(window);
let terrainOn=0;const raw=new Float32Array(7),Gym=load('assets/brace-equipment-plugin.js').commands.GymEquipment;const gym=new Gym('test',{catalog:{}},{readOnnxSlot:({command})=>command==='terrain'?new Float32Array([terrainOn]):raw});
function key(type,key){const e=new Event(type);e.key=key;e.repeat=false;window.dispatchEvent(e)}
key('keydown','s');assert(source.getCommand()[0]<0);raw[1]=5;gym.updateSteeringLock();assert.deepEqual(window.BraceSteering.blockedKeys,['s','a','d','q','e']);assert.match(window.BraceSteering.reasons.s,/Backward movement opposes the forward hand push/);assert.equal(messages.at(-1).forward,0);key('keydown','s');assert.equal(source.getCommand()[0],0);
key('keydown','w');assert(source.getCommand()[0]>0);assert.equal(messages.at(-1).speed_limit,null);key('keydown','a');assert.equal(source.getCommand()[1],0);assert.equal(messages.at(-1).speed_limit,null);source.setCommand(.8,.3,6);assert.deepEqual(source.getCommand(),[.8,0,0]);assert.match(window.BraceSteering.reasons.a,/Sideways and diagonal/);assert.equal(messages.at(-1).movement_profile,'exertion');key('keyup','a');raw[1]=-5;gym.updateSteeringLock();assert.deepEqual(window.BraceSteering.blockedKeys,['w','s','a','d','q','e']);assert.equal(source.getCommand()[0],0);
key('keydown','q');assert.equal(source.getCommand()[0],0);assert.equal(source.getCommand()[2],0);assert.match(window.BraceSteering.reasons.q,/can cause a fall/);source.setCommand(.4,0,20);assert.equal(source.getCommand()[2],0);key('keyup','q');key('keydown','s');assert.equal(source.getCommand()[0],0);assert.match(window.BraceSteering.reasons.s,/caused falls even at the slow step/);source.setCommand(-.4,0,0);assert.equal(source.getCommand()[0],0);key('keyup','s');
raw.fill(0);raw[2]=5;gym.updateSteeringLock();assert(window.BraceSteering.blockedKeys.includes('d'));assert(window.BraceSteering.blockedKeys.includes('w'));assert(window.BraceSteering.blockedKeys.includes('q'));assert.match(window.BraceSteering.reasons.w,/caused falls in testing/);source.setCommand(.4,0,20);assert.deepEqual(source.getCommand(),[0,0,0]);key('keydown','d');assert.equal(source.getCommand()[1],0);key('keydown','a');assert(source.getCommand()[1]>0);assert.equal(messages.at(-1).speed_limit,.18);
raw[2]=-5;gym.updateSteeringLock();assert(window.BraceSteering.blockedKeys.includes('a'));assert.equal(source.getCommand()[1],0);
raw.fill(0);raw[3]=5;gym.updateSteeringLock();assert.deepEqual(window.BraceSteering.blockedKeys,['s','a','d']);source.setCommand(.4,0,20);assert.equal(source.getCommand()[2],10);assert.equal(messages.at(-1).speed_limit,.5);assert.equal(messages.at(-1).movement_profile,'exertion_vertical');source.setCommand(0,0,10);assert.equal(source.getCommand()[2],0);source.setCommand(.4,.3,10);assert.deepEqual(source.getCommand(),[.4,0,10]);terrainOn=1;gym.updateSteeringLock();assert.deepEqual(source.getCommand(),[0,0,0]);assert(window.BraceSteering.blockedKeys.includes('w'));source.setCommand(.4,0,10);assert.deepEqual(source.getCommand(),[0,0,0]);assert.match(window.BraceSteering.reasons.q,/ramp caused falls/);terrainOn=0;gym.updateSteeringLock();source.setCommand(.4,0,10);assert.deepEqual(source.getCommand(),[.4,0,10]);assert(!window.BraceSteering.blockedKeys.includes('w'));raw[3]=-5;gym.updateSteeringLock();assert.equal(source.getCommand()[2],0);assert.match(window.BraceSteering.reasons.q,/Downward/);raw[3]=5;gym.updateSteeringLock();key('keydown','q');raw[1]=5;gym.updateSteeringLock();assert.equal(source.getCommand()[2],0);key('keyup','q');
raw[1]=5;raw[4]=-5;gym.updateSteeringLock();assert(window.BraceSteering.blockedKeys.includes('w')&&window.BraceSteering.blockedKeys.includes('s'));source.setCommand(1,0,0);assert.equal(source.getCommand()[0],0);
window.BraceExert.enabled=false;gym.updateSteeringLock();assert.deepEqual(window.BraceSteering.reasons,{});assert.deepEqual(window.BraceSteering.blockedKeys,[]);key('keydown','s');assert(source.getCommand()[0]<0);key('keyup','s');key('keydown','q');assert(source.getCommand()[2]>0);key('keyup','q');source.detachKeys();
source.detachKeys=null;source.attachKeyboard(window);window.BraceExert.enabled=true;raw.fill(0);raw[4]=5;terrainOn=1;
gym.slopeMocap=0;gym.context.mjData={mocap_quat:new Float64Array(4)};
function ramp(angle,yaw=0){const p=angle*Math.PI/360,h=yaw*Math.PI/360;gym.context.mjData.mocap_quat.set([Math.cos(p)*Math.cos(h),Math.sin(p)*Math.sin(h),-Math.sin(p)*Math.cos(h),Math.cos(p)*Math.sin(h)]);gym.updateSteeringLock()}
ramp(10);key('keydown','w');assert.equal(messages.at(-1).movement_profile,'exertion_slope');assert.equal(messages.at(-1).speed_limit,null);assert(source.getCommand()[0]>0);
raw[4]=8;gym.updateSteeringLock();assert.equal(source.getCommand()[0],0);assert.match(window.BraceSteering.reasons.w,/current ramp caused falls/);source.setCommand(.8,0,20);assert.deepEqual(source.getCommand(),[0,0,0]);assert.equal(messages.at(-1).movement_profile,'exertion');
key('keyup','w');ramp(8,120);source.setCommand(.8,0,20);assert.deepEqual(source.getCommand(),[.8,0,0]);assert.equal(messages.at(-1).movement_profile,'exertion_slope');
raw[1]=8;gym.updateSteeringLock();source.setCommand(.8,0,0);assert.deepEqual(source.getCommand(),[0,0,0]);raw[1]=0;raw[4]=9;ramp(6);source.setCommand(.8,0,0);assert.deepEqual(source.getCommand(),[0,0,0]);
raw[1]=raw[4]=5;ramp(10);source.setCommand(.8,0,0);assert.deepEqual(source.getCommand(),[.8,0,0]);terrainOn=0;raw[4]=8;gym.updateSteeringLock();source.setCommand(.8,0,0);assert.equal(messages.at(-1).movement_profile,'exertion');source.detachKeys();
console.log('PASS opposing keyboard and direct commands blocked, held input stopped, horizontal Q/E blocked and held turns stopped, vertical turn retained, lateral/vertical/two-hand directions and clear restore');
